name: ci
on:
  - pull_request
  - push

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
        node_version:
          - 10
          - 12
          # - 14
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci

  Test-gyp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 12
          - 14
          - 16

    steps:
      - run: npm install node-gyp
      - run: npm install -g node-pre-gyp
      - run: npm install -g node-pre-gyp-github
      - run: npm install --build-from-sources
      - run: npx node-pre-gyp configure
      - run: npx node-pre-gyp build
      - run: npx node-pre-gyp package

  Deploy-gyp:
    if: github.ref == 'refs/heads/master'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 12
          - 14
          - 16

    steps:
      - run: npm install node-gyp
      - run: npm install -g node-pre-gyp
      - run: npm install -g node-pre-gyp-github
      - run: npm install --build-from-sources
      - run: npx node-pre-gyp configure
      - run: npx node-pre-gyp build
      - run: npx node-pre-gyp package
      - run: npx node-pre-gyp-github publish --release
